version: '3.7'

services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./friendly/:/usr/src/friendly/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev

  celery:
    restart: always
    build:
      context: .
    command: celery -A friendly worker -l debug
    volumes:
      - ./friendly/:/usr/src/friendly/
    env_file:
      - .env.dev
    depends_on:
      - api
      - redis

  redis:
    image: redis:6-alpine

volumes:
    postgres_data:
