# Generated by Django 3.2.6 on 2021-08-26 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
