# Generated by Django 3.2.6 on 2021-08-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_post_author_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
