# Generated by Django 3.2.6 on 2021-08-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='example@mail.com', max_length=50, unique=True),
        ),
    ]
