# Generated by Django 3.2.6 on 2021-08-26 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
