# Generated by Django 3.2.6 on 2021-08-26 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@mail.com', max_length=50, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
