# Generated by Django 3.2.6 on 2021-08-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
