# Generated by Django 3.2.6 on 2021-08-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
