# Generated by Django 3.2.6 on 2021-08-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_geodata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='geodata',
            new_name='geo_data',
        ),
    ]
