# Generated by Django 3.2.6 on 2021-08-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_user_geo_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
