# Generated by Django 3.2.6 on 2021-08-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210827_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
